npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "20F1906A-9DF0-4914-951C-E52CDAAE2CC3"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "20F1906A-9DF0-4914-951C-E52CDAAE2CC3"